### ISSUE TITLE
Python dev dependency installation failed

### ISSUE THREAD

**Issue by csabaszilveszter** [naftulikay/ansible-role-python-dev#16]
Using `- naftulikay.python-dev, v2.0.1`:

```
TASK [naftulikay.python-dev : install python dev dependencies] **************************************************************
failed: [localhost] (item=dict_values(['libffi-dev', 'libxml2-dev', 'libxslt1-dev', 'libyaml-dev'])) => {"changed": false, "item": "dict_values(['libffi-dev', 'libxml2-dev', 'libxslt1-dev', 'libyaml-dev'])", "msg": "No package(s) matching 'dict_values(['libffi-dev'' available"}
```

Seems like changing this line in `tasks/main.yml` from
```
  with_items: "{{ python_dev_packages.values() }}"
```
to 
```
  with_items: "{{ python_dev_packages.values() | list }}"
```
fixes the issue.

**Comment by naftulikay** [comment]
Thank you. I'll try to get this into `master` ASAP. 

What's your Ansible version, Python version, host OS, and guest OS?

**Comment by naftulikay** [comment]
It's been a lot to support installation of arbitrary system/pip packages, so I have stripped that out of the latest release. It's likely not ever going to be addressed, sadly. If this is still valuable to you, please describe your use-case and we can discuss opening up a `2.x` branch for supporting major release 2.
